addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-git"         % "2.0.1")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"        % "2.5.3")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"    % "3.11.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp"         % "2.2.1")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin" % "1.1.3")
