addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.6.2")
addSbtPlugin("com.github.sbt" % "sbt-git"         % "2.2.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"        % "2.9.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp"         % "2.3.2")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin" % "1.2.0")
