name: PR Validation
on: pull_request

jobs:
  scalaFmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache SBT & ivy cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - uses: sbt/setup-sbt@v1
      - name: Check formatting
        run: sbt scalafmtCheckAll

  test:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache SBT & ivy cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - uses: sbt/setup-sbt@v1
      - name: Compile and test
        run: sbt docs/mdoc +test +doc version +mimaReportBinaryIssues
